In [ ]:
# EXPERIMENT 10 STUDY OF PANDAS LIBRARY
# PALLAWI KUMARI 25070123083

In [ ]:
# INTRODUCTION TO PANDAS
# PANDAS : PANEL DATA
'''Used for:
Structured data

In [2]:
import pandas as pd

s = pd.Series([10,20,30,40,50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [5]:
#create dataframe
data = {
    "Name":["a","b","c"],
    "Marks":[10,20,30]
}
df = pd.DataFrame(data)
print(df)

  Name  Marks
0    a     10
1    b     20
2    c     30

In [6]:
df.shape

(3, 2)

In [7]:
df.ndim

2

In [8]:
df.size

6

In [9]:
#display column names
df.columns

Index(['Name', 'Marks'], dtype='object')

In [10]:
#check data types of each column
df.dtypes

Name     object
Marks     int64
dtype: object

In [12]:
# access individual column
df["Name"]

0    a
1    b
2    c
Name: Name, dtype: object

In [13]:
# access name of first row
df.loc[0,"Name"]

'a'

In [16]:
df = pd.DataFrame(data)
print(df)
print(df.loc[0,"Name"])
print(df.iloc[2,1])

  Name  Marks
0    a     10
1    b     20
2    c     30
a
30

In [17]:
#add a new column

df["Grade"] = ["first class","distinction","second class"]
print(df)

  Name  Marks         Grade
0    a     10   first class
1    b     20   distinction
2    c     30  second class

In [18]:
#update data in data frame
# change marks of student a to 88
df.loc[0,"Marks"] = 88
print(df)

  Name  Marks         Grade
0    a     88   first class
1    b     20   distinction
2    c     30  second class

In [20]:
#delete a column
#df.drop("Grade", axis=1, inplace=True)
df1=df.drop("Grade", axis=1)
print(df)
print(df1)

  Name  Marks         Grade
0    a     88   first class
1    b     20   distinction
2    c     30  second class
  Name  Marks
0    a     88
1    b     20
2    c     30

In [21]:
#perform basic statistical analysis
mean1=df["Marks"].mean()
mean1

np.float64(46.0)

In [22]:
min1=df["Marks"].min()
min1

20

In [23]:
max1=df["Marks"].max()
max1

88

In [25]:
#apply condition (filtering)
df[df["Marks"]>80]

  Name  Marks        Grade
0    a     88  first class